serve:
  controller:
    login-url: /api/login
    logout-url: /api/logout
    api-prefix: /api
    open-prefix: /open
    # noinspection SpringBootApplicationYaml
    prefix-configs:
      - prefix: /api
        package-name: com.tempest.serve.controller.api
      - prefix: /open
        package-name: com.tempest.serve.controller.open
spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
  data:
    redis:
      jedis:
        pool:
          enabled: true
          min-idle: 5
          max-idle: 10
          max-wait: 20000
          max-active: 10
  profiles:
    active: dev
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.tempest.serve.pojo.entity