spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
  data:
    redis:
      jedis:
        pool:
          enabled: true
          min-idle: 5
          max-idle: 10
          max-wait: 20000
          max-active: 10
  profiles:
    active: dev